sodadata/soda-spark

README.md

- Fixes #10
- Fixes #11
- Fixes #12

Add project description and high level api toreadme

---

README.md

Add scan api to readme usage guide

---

README.md
setup.cfg

Use doctest

---

.github/workflows/test.yml
.gitignore
pyproject.toml
setup.cfg
setup.py
tox.ini

Use tox for testing

---

README.md
setup.py
src/sodaspark/scan.py
tests/test_scan.py

Let execute return scan results

---

.github/workflows/workflow.yml

It was *master* but it should be main

Let github CI trigger on main branch

---

tests/test_scan.py

Test scan results has no errors

---

tests/test_scan.py

Test if column metrics work

---

tests/test_scan.py

Add test with metric groups

---

tests/test_scan.py

Add test to show excluded columns works

---

README.md
src/sodaspark/scan.py
tests/test_scan.py

Accept yml string instead of file

---

.pre-commit-config.yaml
scripts/release.py
src/sodaspark/scan.py
tests/test_scan.py

Update pre-commit config and resolve issues

---

.github/workflows/test.yml

Did not find the correct version due to missing setuptools-scm

Add install setuptools-scm

---

.github/workflows/test.yml
CHANGELOG.md
scripts/release.py

Add changelog

---

tests/test_scan.py

Remove equality methods in test

---

src/sodaspark/scan.py

Mock cursor and connection

---

CHANGELOG.md
README.md
src/sodaspark/scan.py
static/demodata.yml
tests/test_scan.py

Add soda server client

---

CHANGELOG.md
README.md
static/demodata.yml
tests/test_scan.py

Add test for sql metrics

---

setup.cfg
setup.py

Remove setup py

---

src/sodaspark/scan.py
static/demodata.yml

Fix samples

---

CHANGELOG.md
setup.cfg
src/sodaspark/scan.py

Use version ranges

---

setup.cfg

- bumping soda-sql-spark to the latest version.

bumping soda-sql-spark to 2.1.9

---

.pre-commit-config.yaml
src/sodaspark/scan.py

- add variable support in soda-spark

add variable support in soda-spark

---

src/sodaspark/scan.py

Add option to pass warehouse_name to execute
